name: click_battle
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/

  fonts:
    - family: Permanent-Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker.ttf
